name: CI/CD to Seonglae Server


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: get-key
      run: |
        echo {{PFX}} | base64 --decode > key.pfx
        echo {{ENV}} > .env


    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-

    - name: Install npm dependencies]
      run: yarn

    - name: Run build task
      run: yarn build

    - uses: actions/upload-artifact@v1
      with:
        name: make artiface
        path: dist
